# Generated by Django 4.0.4 on 2022-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
    ]
