# Generated by Django 4.0.4 on 2022-04-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_song_is_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='midigenerated',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
